### ISSUE TITLE
Problem on Windows seems to be related to gevent

### ISSUE THREAD

**Issue by reszelaz** [ALBA-Synchrotron/pytango-db#4]
After the following installation:
```
pip install pytango-db
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pytango-db
  Downloading https://files.pythonhosted.org/packages/52/11/25aa7e9b69c4e3ece42198085d0733cdf86e48c954ed1cba6b42f63b91aa/pytango-db-0.2.0.tar.gz
Requirement already satisfied: PyTango in c:\lib\site-packages (from pytango-db) (9.2.3)
Collecting gevent (from pytango-db)
  Downloading https://files.pythonhosted.org/packages/5b/16/34bb535206f9eee9ab87647575b7704dba23aca6201a5a1739dcd036a1ca/gevent-1.4.0-cp27-cp27m-win_amd64.whl (3.0MB)
Collecting futures (from pytango-db)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Requirement already satisfied: six in c:\miniconda-x64\envs\py2qt5\lib\site-packages (from PyTango->pytango-db) (1.12.0)
Collecting cffi>=1.11.5; sys_platform == "win32" and platform_python_implementation == "CPython" (from gevent->pytango-db)
  Downloading https://files.pythonhosted.org/packages/fa/24/37ec704b98ffc36e7d0ade9e4653539c0b8e6fec34f084f30194609aa10b/cffi-1.12.3-cp27-cp27m-win_amd64.whl (168kB)
Collecting greenlet>=0.4.14; platform_python_implementation == "CPython" (from gevent->pytango-db)
  Downloading https://files.pythonhosted.org/packages/94/2e/36d4aa9fc190695f67b5d4918f72f2c5beca7edd3b52bc496973954bcc5d/greenlet-0.4.15-cp27-cp27m-win_amd64.whl
Collecting pycparser (from cffi>=1.11.5; sys_platform == "win32" and platform_python_implementation == "CPython"->gevent->pytango-db)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Building wheels for collected packages: pytango-db, pycparser
  Building wheel for pytango-db (setup.py): started
  Building wheel for pytango-db (setup.py): finished with status 'done'
  Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\fa\f8\49\f679f6a4278e07acb0a069bd02fecdea37100a67854e1e4b87
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\f2\9a\90\de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pytango-db pycparser
Installing collected packages: pycparser, cffi, greenlet, gevent, futures, pytango-db
Successfully installed cffi-1.12.3 futures-3.2.0 gevent-1.4.0 greenlet-0.4.15 pycparser-2.19 pytango-db-0.2.0
```

I tried this on Windows and have the following error:

```
Exiting: Server exited with tango.DevFailed:
DevFailed[
DevError[
    desc = AttributeError: 'module' object has no attribute 'Event'
           
  origin =   File "c:\miniconda-x64\envs\py2qt5\lib\site-packages\tangodb\database.py", line 1820, in device_factory
    device = self._new_device(deviceImplClass, klass, dev_name)
  File "C:\Lib\site-packages\tango\device_class.py", line 547, in __DeviceClass__new_device
    return klass(dev_class, dev_name)
  File "C:\Lib\site-packages\tango\server.py", line 571, in __init__
    self.init_device()
  File "C:\Lib\site-packages\tango\server.py", line 360, in init_device
    return get_worker().execute(init_device_orig, self)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 183, in execute
    task = self.submit(fn, *args, **kwargs)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 177, in submit
    return self.loop.submit(fn, *args, **kwargs)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 145, in submit
    event = gevent._threading.Event()
  reason = PyDs_PythonError
severity = ERR]
]
Traceback (most recent call last):
  File "C:\Lib\site-packages\tango\server.py", line 1479, in run
    return server_run()
  File "C:\Lib\site-packages\tango\server.py", line 1335, in __server_run
    worker.run(tango_loop, wait=True)
  File "C:\Lib\site-packages\tango\green.py", line 101, in run
    return self.access(accessor, timeout=timeout)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 174, in access
    return accessor.get(timeout=timeout)
  File "src\gevent\event.py", line 268, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 296, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 286, in gevent._event.AsyncResult.get
  File "src\gevent\event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "c:\miniconda-x64\envs\py2qt5\lib\site-packages\gevent\threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
  File "C:\Lib\site-packages\tango\server.py", line 1329, in tango_loop
    util.server_init()
DevFailed: DevFailed[
DevError[
    desc = AttributeError: 'module' object has no attribute 'Event'
           
  origin =   File "c:\miniconda-x64\envs\py2qt5\lib\site-packages\tangodb\database.py", line 1820, in device_factory
    device = self._new_device(deviceImplClass, klass, dev_name)
  File "C:\Lib\site-packages\tango\device_class.py", line 547, in __DeviceClass__new_device
    return klass(dev_class, dev_name)
  File "C:\Lib\site-packages\tango\server.py", line 571, in __init__
    self.init_device()
  File "C:\Lib\site-packages\tango\server.py", line 360, in init_device
    return get_worker().execute(init_device_orig, self)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 183, in execute
    task = self.submit(fn, *args, **kwargs)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 177, in submit
    return self.loop.submit(fn, *args, **kwargs)
  File "C:\Lib\site-packages\tango\gevent_executor.py", line 145, in submit
    event = gevent._threading.Event()
  reason = PyDs_PythonError
severity = ERR]
]
Exited
```

It's strange since on Linux it works with the same version of gevent without problems:

```
:~> python -c "import gevent; print(gevent.__version__)"
1.4.0
:~> DataBaseds --db_access=sqlite3 --port=20000 2
Ready to accept request
```
Any clue?

**Comment by reszelaz** [comment]
To work with PyTango 9.2.3 one needs gevent not higher then 1.2.2. Thanks @tiagocoutinho !
